Repository JushBJJ/Mr.-Ranedeer-AI-Tutor, pull requests merged in 2023-05, with the labels that each got.

#8 Change JSON to YAML
  Mr_Ranedeer.yaml
  README.md
Labels: enhancement

#9 Add language configuration
  Mr_Ranedeer.json
  README.md
  docs.md
Labels: enhancement, help wanted

#16 feat: added markdown format
  Mr_Ranedeer.md
  README.md
Labels: documentation, enhancement
